### ISSUE TITLE
Problem in Windows installation due to spaces in library file path

### ISSUE THREAD

**Issue by mtiezzi** [BTNC/distro-win#10]
Hi, I'm trying to install torch on Windows 10 64 bit. I've installed all programs required, but I got an error during installation (using install.bat), and I am not able to solve it. 
I will attach the log of the error

[logtorchwin.txt](https://github.com/BTNC/distro-win/files/622444/logtorchwin.txt)

**Comment by BTNC** [comment]
It is due to blas\lapack libraries' path are not handled properly when they have spaces. The fix has been checked in. Please git pull latest changes and retry. Thanks for the report.

**Comment by mtiezzi** [comment]
You're welcome.
Thank you very much it solved the problem, the installation succeded.
I'll close the issue.
I'd also like to report some bugs I found. I report them here, however if you want me to open another issue tell me.

- If you require 'sys' inside th, it "breaks" the colors  of the terminal
![color1](https://cloud.githubusercontent.com/assets/24276199/20789730/d6a25338-b7b5-11e6-9665-897c5bd80baf.png)

- If you use tab inside th to suggest a folder, it ask if you want to exit (firsts rows of the second screen).
- Trying to import a three dimension dataset (working using torch installed via bash on Ubutnu on Windows) it doesn't work.

![bug1](https://cloud.githubusercontent.com/assets/24276199/20789834/36f76a3e-b7b6-11e6-8ea8-7812e4bcb52b.png)

However thanks  for your efforts in developing this , Windows needs torch!

**Comment by BTNC** [comment]
'th' on windows is not as fascinating as its counter party on *nix systems. I know those 'bugs' but I did not spend much time investigating them as long as they are not blockers to use torch.

The dataset problem is due to sizeof(long) is 32 bit on windows while is 64 bit on linux and macos. I did update torch's memory size/offset, element count etc from long to ptrdiff_t, but I did not touch longtensor and longstorage. It will not be a problem if you use float tensor (I can not guarantee, at least I did not encounter problems). If 32 bit long tensor is enough, you can try the [torch.DiskFile.longSize() api](https://github.com/torch/torch7/blob/6acd647cfc6617d09dedea1d00385fef6c9e3984/doc/diskfile.md#longsizesize). However if you depend on 64 bit long tensor, you have to switch back to your ubuntu torch. Torch owner expressed the idea to update torch's type usages(like long -> int64_t), however as it is not a blocker for users on linux and macos, we may not see the update in foreseeing future.

**Comment by mtiezzi** [comment]
Thank you very much
