### ISSUE TITLE
Have to run torch-activated.cmd

### ISSUE THREAD

**Issue by Chunde** [BTNC/distro-win#13]
It seems if I need to use torch, i have to run the 'torch-activate.cmd' every time, and should start from the install path.

**Comment by BTNC** [comment]
> It seems if I need to use torch, i have to run the 'torch-activate.cmd' every time

Yes, if you close the command prompt every time you finish use Torch. Torch is installed in a self contained folder so that it is not messed with other luajit/luarocks installations for non torch use cases, and other torch installations with different versions of lua. 'torch-activate.cmd' is used to setup which lua/luajit torch installation is going to be used afterwards.

>  and should start from the install path.

Not necessary, you can run the full path of 'torch-activate.cmd' from any directory and use Torch afterwards.

**Comment by Chunde** [comment]
@howard0su Thanks very much! 
Now I close this issue.
