### ISSUE TITLE
install error with wineditline

### ISSUE THREAD

**Issue by ketigid** [BTNC/distro-win#6]
Hi,

I've encountered installation error with both x86 and x64 installation. Both processes are terminated when compiling readline.obj.

I looked in win-files/3rd folder and found that the wineditline-2.101 folder does not exist. The wineditline.zip file unzips to a wineditline file without file extensions. Using 7-zip to open the wineditline file reveals a wineditline-2.201 folder inside, which is inconsistent with the wineditline-2.101 folder being referenced during the installation.

**Comment by BTNC** [comment]
It turns out wget is now getting tar.bz2 file instead of the zip file from default link, and the downloaded file is not properly unzipped. This repo has been updated to download the zip file. And trepl has been updated to refer to wineditline-2.201.
Thanks for the report!

Please remove 3rd/wineditline* and retry.
