### ISSUE TITLE
Cannot luarocks install cutorch

### ISSUE THREAD

**Issue by andreazugarini** [BTNC/distro-win#9]
Hi, I installed torch, but I get the following error when it tries to install cutorch:

> cmake -E make_directory build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="C:/Users/Andrea/distro-win/./install/bin/.." -DCMAKE_INSTALL_PREFIX="C:\Users\Andrea\distro-win\.\install\luarocks\systree/lib/luarocks/rocks/cutorch/scm-1" && nmake -j$(getconf _NPROCESSORS_ONLN) install
> 
> -- The C compiler identification is MSVC 19.0.24210.0
> -- The CXX compiler identification is MSVC 19.0.24210.0
> -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe
> -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe
> -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Found Torch7 in C:/Users/Andrea/distro-win/install
> CMake Warning (dev) at C:/Program Files/CMake/share/cmake-3.7/Modules/FindCUDA.cmake:490 (if):
>   Policy CMP0054 is not set: Only interpret if() arguments as variables or
>   keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
>   details.  Use the cmake_policy command to set the policy and suppress this
>   warning.
> 
>   Quoted variables like "MSVC" will no longer be dereferenced when the policy
>   is set to NEW.  Since the policy is not set the OLD behavior will be used.
> Call Stack (most recent call first):
>   CMakeLists.txt:7 (FIND_PACKAGE)
> This warning is for project developers.  Use -Wno-dev to suppress it.
> 
> -- Found CUDA: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v8.0 (found suitable version "8.0", minimum required is "6.5")
> -- MAGMA not found. Compiling without MAGMA support
> -- Autodetected CUDA architecture(s): 5.0
> -- got cuda version 8.0
> -- Found CUDA with FP16 support, compiling with torch.CudaHalfTensor
> -- CUDA_NVCC_FLAGS: -gencode;arch=compute_50,code=sm_50;-Xcompiler /wd4819;-DCUDA_HAS_FP16=1
> -- Configuring done
> -- Generating done
> -- Build files have been written to: C:/Users/Andrea/AppData/Local/Temp/luarocks_cutorch-scm-1-130/cutorch/build
> 
> Microsoft (R) Program Maintenance Utility Version 14.00.24210.0
> Copyright (C) Microsoft Corporation.  All rights reserved.
> 
> NMAKE : fatal error U1065: invalid option 'j'
> Stop.
> 
> Error: Build error: Failed building.
>

**Comment by BTNC** [comment]
It seems you are trying to run "luarocks install _some_package_", and _some_package_ depends on cutorch. It is not working because the command will refer to an online out-of-date rockspec mentioned in the last line of your error output. Besides, the patch for cunn is not merged to torch/cunn, cunn maybe compiled but may not work in a few cases.

To install cutorch, cunn, etc for msvc manually, I suggest you refer to [these lines in install.bat](https://github.com/BTNC/distro-win/blob/master/install.bat#L44)

**Comment by andreazugarini** [comment]
> To install cutorch, cunn, etc for msvc manually, I suggest you refer to these lines in install.bat

Great, now it works, I was able to install both.
For others that may face the same problem here is how I did (trough windows command prompt):

1. go into _.\distro-win\extra_
2. download _cutorch_ into using git:    `git clone https://github.com/torch/cutorch`
3. go into _.\distro-win\extra\cutorch_
4. edit the file in _.\rocks\cutorch-scm-1.rockspec_ removing the option _-j jopts_ (line 26)
5. run the command `call .\distro-win\install\luarocks.cmd make rocks\cutorch-scm-1.rockspec` 

same procedure for _cunn_ .

**Comment by BTNC** [comment]
Thanks @zugo91 for posting your procedure. However in case anyone is mislead, I need to edit your issue title and update your procedure as below, and the procedure is only applicable for those run install.bat without cuda setup and now want to install cutorch, cunn after cuda has been setup.
1. the simplest way is to run install.bat again to install a fresh new torch7, however this will discard changes in your existing torch7 if new torch7 is installed in the same dir;
2. To install cutorch manually, go to .\distro-win\extra\cutorch, and run `luarocks make rocks\cutorch-scm-1.rockspec`, please refer to [ these lines of install.bat](https://github.com/BTNC/distro-win/blob/master/install.bat#L44) and [README](https://github.com/BTNC/distro-win/tree/master/win-files) if you have trouble with these commands;

> download cutorch into using git: git clone https://github.com/torch/cutorch

It is not suggested to `git clone` branch master from `torch/cutorch` since latest code is not guaranteed to compile or work correctly with msvc. Instead if you ever run install.bat, cutorch's source is already under _.\distro-win\extra_.

> edit the file in .\rocks\cutorch-scm-1.rockspec removing the option -j jopts (line 26)

There is no need to edit the rockspec, [line 32](https://github.com/torch/cutorch/blob/master/rocks/cutorch-scm-1.rockspec#L32) will be run for windows instead of line 26(27).
